# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket         = "awanmasterpiece-terraform-state"
    encryption_key = ""
    prefix         = "./dev/terraform.tfstate"
  }
}
