# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.0.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 4.80.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 4.80.0"
    }
  }
}

provider "google" {
  project = "awanmasterpiece-dev"
  region  = "asia-southeast2"
}

provider "google-beta" {
  project = "awanmasterpiece-dev"
  region  = "asia-southeast2"
}
